# Generated by Django 5.2.3 on 2025-07-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('js', 'JavaScript'), ('cpp', 'C++')], max_length=10),
        ),
    ]
