# Generated by Django 5.2.3 on 2025-07-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_snippet_description_alter_snippet_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
