# Generated by Django 5.2.3 on 2025-07-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_alter_snippet_options_remove_snippet_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
