# Generated by Django 5.2.3 on 2025-08-25 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_snippetsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['name', 'lang'], name='MainApp_sni_name_48c470_idx'),
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['lang', 'name'], name='MainApp_sni_lang_6d4319_idx'),
        ),
    ]
